### ISSUE TITLE
Indentation with macros

### ISSUE THREAD

**Issue by ajitid** [ZhiyuanLck/smart-pairs#5]
A macro recording of 

```js
const a = [

]
```

results in this when the macro is executed:

```js
const a = []
```

**Expected behaviour**

To get exactly the result of what I recorded the macro with.

**Comment by ZhiyuanLck** [comment]
It seems that macro display does not respect something like `feedkeys("\<cr>", 'n')`, it can be reproduced by `imap <cr> <cmd>feedkeys("\<cr>", 'n')` and type `<cr>` when you record a macro.

I have no idea if it is a bug or the normal behaviour of vim. But it may be avoided by not feeding `<cr>` in the mapping. Current implementation of smart enter is quite simple and it may change to use `append` to insert a newline and handle the indentation in the future rather than depending on the original enter.

**Comment by ZhiyuanLck** [comment]
Now when you type enter inside an empty brackets, the action is recorded but the `<tab>` fed to correct indentation is still ignored.

**Comment by ajitid** [comment]
Hey @ZhiyuanLck just checked and it works well. But it has created another issue — closing bracket doesn't correctly indents.

![anim-rg](https://user-images.githubusercontent.com/26769888/153744250-001dcd46-8ba6-4cc4-8eee-9c4ab318edb7.gif)

**Comment by ajitid** [comment]
Can confirm it works now with the commit you pushed, than you!
